# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65ff7664fa7fe7b675656dbbf68652a886cc9130ac1a6fc045d21d55effc10a4a374db0bc3bfd519396cbb93977024d8b6d36096098a370c218b96c1e875df4c

test:
  secret_key_base: 8594122bc4517a0ee032e6324c8a96f876bffd2cd6a557f3cc5b2a94dadfad4babe89d592f5a5499bcaf2bffe30ebae3b7b4a336aeefbba4cb7727279956db13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
